[package]
name = "white_noise_player_v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kira = "0.6.0"
casual_logger = "0.6.5"